### PR TITLE
Optional exceptions and shader overrides

### PR DESCRIPTION
**Pull request by bazhenovc**
Hi!

I needed a text rendering library for my engine, and ive found gltext.
However i dont use c++ exceptions there and i need to have custom shaders for text, so here they are :)

### CODE REVIEW

**Comment by branan** [comment]
I like both of these concepts, but I'm not sure I want to go with your implementations.

For the exceptions, it looks like you've completely stripped error handling in the non-exception use case. I'd prefer to see some sort of error handling put in place of the removed exceptions. A big mean example: all the functions that throw an error if self is NULL will segfault with your patch applied. The initialization function also needs to be adjusted so that it can safely bail out and set self to NULL in case there's an error.

You also cleaned up all the awful white space my text editor left behind, which is awesome, but it makes the diff a mess.

For the shader programs, setShaders can only be called once, and it must be called before any text objects are created. I do like the idea of being able to override the default, but I think I'm going to take the time to make a more flexible way to handle shader objects.

**Comment by bazhenovc** [comment]
Yes, my implementations are messy. Haste makes waste :) If you want, i can rewrite exception-related code.

**Comment by branan** [comment]
If you'd be interested in writing a more robust exception-free error handling system, I'd be happy to merge it. Otherwise I can add it to my own TODO list.

**Comment by bazhenovc** [comment]
Ok, i will do that.

**Pull request closed without merging**
